baseURL : '/ACMEK'
languageCode : 'es-es'
title : 'ACME-Jordan'
theme : 'Codex'


menu:
  main:
    - identifier: about
      name: About
      url: /menu/acerca_de/
      weight: 200 
    - identifier: contact
      name: Contacto 
      url: /menu/contacto/
      weight: 200 
    - identifier: viajes
      name: Viajar
      url : /viajes/viajar/
      weight: 200
    - identifier: blog
      name: Blog
      url : /blog/blogmain/
      weight: 200


